---
version: 2
jobs:
  build:
    docker:
      - image: ruby:2.6.2
        environment:
          RAILS_ENV: test
      - image: mongo:4.1.13
      - image: mysql:8.0.16
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_USER: root
        port: 3306:3306
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec
