---
version: 2
jobs:
  build:
    docker:
      - image: ruby:2.6.2
        environment:
          RAILS_ENV: test
      - image: mongo:4.1.13
      - image: rabbitmq
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec
