default: &default
  DEEP_THOUGHT__LOG_LEVEL: INFO
  DEEP_THOUGHT__RAILS_LOG_TO_STDOUT: true
  DEEP_THOUGHT__DB_URI: mongodb://localhost:27017/deep_thought
test: &test
  <<: *default
  DEEP_THOUGHT__LOG_LEVEL: ERROR
  DEEP_THOUGHT__DB_URI: mongodb://localhost:27017/deep_thought_test
development: &development
  <<: *default
  DEEP_THOUGHT__LOG_LEVEL: DEBUG
  DEEP_THOUGHT__DB__URI: mongodb://localhost:27017/deep_thought_development
production: &production
  <<: *default